---
title: "Final Bat Paper R Markdown"
author: "Steph"
date: "08/03/2023"
output: html_document
---

```{r Library Imports, message=FALSE, warning=FALSE}
library(ggplot2)
library(data.table)
library(readr)
library(reshape2)
library(vegan)
library(zoo)
library(tidyverse)
```


```{r setup, echo=FALSE}
getwd()

setwd("/Users/stephaniewaller/Desktop/Bat")
```

```{r make stacked kingdom normalised, standardised abundance estimates}
#Import data
kingdom <- read.csv("kingdom_standardised_abundance.csv", header=TRUE)
kingdom

# Need library ggplot2

#Select only the standardized abundance columns 
bat.data = kingdom[, 2:6]
bat.data

#transpose data
t.data = t(bat.data)
t.data

#melt data into long data frame format
melt.t.data = melt(t.data)
melt.t.data

melt.t.data <- melt.t.data[-(61:140),]
melt.t.data

colnames(melt.t.data) = c("Kingdom", "Library", "Standardised_abundance")

melt.t.data

#Make stacked bar plot with normalised standardised data
standard = ggplot(melt.t.data, aes(fill=Kingdom, y=Standardised_abundance, x=Library)) + 
    geom_bar(position="fill", stat="identity")
standard

```

```{r Alpha Diversity species- shannon vertebrate metagenome and bat viruses combined}
vertebrate.metagenome <- read.csv("vertebrate_metagenome_standardised_abundance.csv")

vertebrate.metagenome

#Select only the standardized abundance columns 
vertebrate.metagenome.abundances = vertebrate.metagenome[, 2:17]
vertebrate.metagenome.abundances

#transpose data
t.vertebrate.metagenome = t(vertebrate.metagenome.abundances)
t.vertebrate.metagenome


# Shannon diversity (by sample)
t.vertebrate.metagenome = as.data.frame(t.vertebrate.metagenome)
t.vertebrate.metagenome

shannon_combined = apply(t.vertebrate.metagenome,2,diversity,index="shannon") 
shannon_combined

# Box plot: Shannon diversity
shannon_matrix = as.matrix(shannon_combined)
shannon_matrix
metadata <- read.csv("vertebrate_standardised_abundance.csv", header=TRUE)
metadata
shannon_matrix_species = cbind(shannon_matrix, metadata$Species)
shannon_matrix_species
colnames(shannon_matrix_species) = c("Shannon", "Species")
shannon_matrix_species


# Extract species
M.tuberculata = shannon_matrix_species[c(1,2,3,4,7,8,11),]
M.tuberculata
C.tuberculatus = shannon_matrix_species[c(5,6,9,10,12),]
C.tuberculatus

# Combine species as separate rows and transpose data

shannon_matrix = t(as.matrix(merge(zoo(M.tuberculata[,1]), zoo(C.tuberculatus[,1]))))
shannon_matrix
class(shannon_matrix) = "numeric"
class(shannon_matrix)
rownames(shannon_matrix) = c("M.tuberculata", "C.tuberculatus")
shannon_matrix

# Transpose and melt
tshannon = t(shannon_matrix)
tshannon
melt_shannon = melt(tshannon)
melt_shannon
colnames(melt_shannon) = c("1", "Species", "Shannon Index")
melt_shannon
#remove extra two rows from C.tuberculatus
melt_shannon <- melt_shannon[-(13:14),]
melt_shannon



# Plot Shannon index by species
shannon_plot_species = ggplot(melt_shannon, aes(x=Species, y=`Shannon Index`, fill=Species)) + 
  geom_boxplot() + geom_jitter(color="black", size=2, alpha=0.2, height=0) + ggtitle("Shannon Index per Species Vertebrate Metagenome")
shannon_plot_species

# Use Welches T-test as it is more reliable when the two samples have unequal variances and possibly unequal sample sizes
M.tuberculata <- c(0.2375336, 0.9305648, 1.1357301, 0.9110898, 0.0000000, 0.6071758, 0.3735534)
C.tuberculatus <- c(0.7238421, 0.4550617, 0.6874913, 0.0000000, 0.0000000)
t.test(M.tuberculata, C.tuberculatus)
#no statistical significance in shannon diversity of vertebrate metagenome viruses between species p-value = 0.3369

```


```{r Alpha Diversity location- shannon vertebrate metagenome and bat viruses combined}
# Shannon diversity (by sample)
t.vertebrate.metagenome = as.data.frame(t.vertebrate.metagenome)
t.vertebrate.metagenome

shannon_combined = apply(t.vertebrate.metagenome,2,diversity,index="shannon") 
shannon_combined

# Box plot: Shannon diversity
shannon_matrix = as.matrix(shannon_combined)
shannon_matrix
metadata <- read.csv("vertebrate_standardised_abundance.csv", header=TRUE)
metadata
shannon_matrix_N_S = cbind(shannon_matrix, metadata$North_South)
shannon_matrix_N_S
shannon_matrix_N_S_species = cbind(shannon_matrix_N_S, metadata$Species)
shannon_matrix_N_S_species
colnames(shannon_matrix_N_S_species) = c("Shannon", "North_South", "Species")
shannon_matrix_N_S_species


# Extract North_South and manually change the dimension of those that only have one row of data
North = shannon_matrix_N_S_species[c(1, 2, 3, 4, 5, 6, 7, 8),]
North
South = shannon_matrix_N_S_species[c(9, 10, 11, 12),]
South

# Combine species as separate rows and transpose data

shannon_matrix_N_S = t(as.matrix(merge(zoo(North[,1]), zoo(South[,1]))))
shannon_matrix_N_S
class(shannon_matrix_N_S) = "numeric"
class(shannon_matrix_N_S)
rownames(shannon_matrix_N_S) = c("North", "South")
shannon_matrix_N_S

# Transpose and melt
tshannon_N_S = t(shannon_matrix_N_S)
tshannon_N_S
melt_shannon_N_S = melt(tshannon_N_S)
melt_shannon_N_S
colnames(melt_shannon_N_S) = c("1", "North_South", "Shannon Index")
melt_shannon_N_S
#remove extra rows from North_South data
melt_shannon_N_S <- melt_shannon_N_S[-c(16, 15, 14, 13),]
melt_shannon_N_S


# Plot Shannon index by Location_Year
shannon_plot_N_S = ggplot(melt_shannon_N_S, aes(x=North_South, y=`Shannon Index`, fill=North_South)) + 
  geom_boxplot() + geom_jitter(color="black", size=2, alpha=0.2, height=0) + ggtitle("Shannon Index per North_South vertebrate metaegenome")
shannon_plot_N_S

# Use Welches T-test as it is more reliable when the two samples have unequal variances and possibly unequal sample sizes
#pvalue= 0.1364 not significant
North <- c(0.2375336, 0.9305648, 1.1357301, 0.9110898, 0.7238421, 0.4550617, 0.0000000, 0.6071758)
South <- c(0.6874913, 0.00000000, 0.3735534, 0.0000000)
t.test(North, South)
```

```{r Alpha Diversity species- shannon bat viruses only}
# Shannon diversity (by sample)
vertebrate <- read.csv("vertebrate_standardised_abundance.csv")
vertebrate

#Select only the standardized abundance columns 
vertebrate.abundances = vertebrate[, 2:8]
vertebrate.abundances

#transpose data
t.vertebrate = t(vertebrate.abundances)
t.vertebrate

t.vertebrate = as.data.frame(t.vertebrate)
colnames(t.vertebrate) = c("B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11", "B12")
t.vertebrate

shannon.vertebrate = apply(t.vertebrate,2,diversity,index="shannon") 
shannon.vertebrate

# Box plot: Shannon diversity
shannon_matrix_v = as.matrix(shannon.vertebrate)
shannon_matrix_v
metadata <- read.csv("vertebrate_standardised_abundance.csv", header=TRUE)
metadata
shannon_matrix_v_species = cbind(shannon_matrix_v, metadata$Species)
shannon_matrix_v_species
shannon_matrix_v_species_location_year = cbind(shannon_matrix_v_species, metadata$Location_Year)
shannon_matrix_v_species_location_year
colnames(shannon_matrix_v_species_location_year) = c("Shannon", "Species", "Location/Year")
shannon_matrix_v_species_location_year


# Extract species
M.tuberculata = shannon_matrix_v_species_location_year[c(1,2,3,4,7,8,11),]
M.tuberculata
C.tuberculatus = shannon_matrix_v_species_location_year[c(5,6,9,10,12),]
C.tuberculatus

# Combine species as separate rows and transpose data

shannon_v_matrix = t(as.matrix(merge(zoo(M.tuberculata[,1]), zoo(C.tuberculatus[,1]))))
shannon_v_matrix
class(shannon_v_matrix) = "numeric"
class(shannon_v_matrix)
rownames(shannon_v_matrix) = c("M.tuberculata", "C.tuberculatus")
shannon_v_matrix

# Transpose and melt
tshannon_v = t(shannon_v_matrix)
tshannon_v
melt_shannon_v = melt(tshannon_v)
melt_shannon_v
colnames(melt_shannon_v) = c("1", "Species", "Shannon Index")
melt_shannon_v
#remove extra two rows from C.tuberculatus
melt_shannon_v <- melt_shannon_v[-(13:14),]
melt_shannon_v



# Plot Shannon index by species
shannon_plot_v = ggplot(melt_shannon_v, aes(x=Species, y=`Shannon Index`, fill=Species)) + 
  geom_boxplot() + geom_jitter(color="black", size=2, alpha=0.2, height=0) + ggtitle("Shannon Index per Species vertebrate")
shannon_plot_v

# Use Welches T-test as it is more reliable when the two samples have unequal variances and possibly unequal sample sizes
M.tuberculata_v <- c(0, 0, 0, 0, 0, 0, 0)
C.tuberculatus_v <- c(0.01267017, 0.29239496, 0.45105090, 0.00000000, 0.00000000)
t.test(M.tuberculata_v, C.tuberculatus_v)
#no statistical significance in shannon diversity of vertebrate viruses between species 

```

```{r Alpha Diversity north/south- shannon bat viruses only}
# Shannon diversity (by sample)
t.vertebrate = as.data.frame(t.vertebrate)
colnames(t.vertebrate) = c("B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11", "B12")
t.vertebrate

shannon.vertebrate = apply(t.vertebrate,2,diversity,index="shannon") 
shannon.vertebrate

# Box plot: Shannon diversity
shannon_matrix_v = as.matrix(shannon.vertebrate)
shannon_matrix_v
metadata <- read.csv("vertebrate_standardised_abundance.csv", header=TRUE)
metadata
shannon_matrix_v_N_S = cbind(shannon_matrix_v, metadata$North_South)
shannon_matrix_v_N_S
colnames(shannon_matrix_v_N_S) = c("Shannon", "North_South")
shannon_matrix_v_N_S

# Extract North_South and manually change the dimension of those that only have one row of data
North_v = shannon_matrix_v_N_S[c(1, 2, 3, 4, 5, 6, 7, 8),]
North_v
South_v = shannon_matrix_v_N_S[c(9, 10, 11, 12),]
South_v

# Combine species as separate rows and transpose data

shannon_matrix_v_N_S = t(as.matrix(merge(zoo(North_v[,1]), zoo(South_v[,1]))))
shannon_matrix_v_N_S
class(shannon_matrix_v_N_S) = "numeric"
class(shannon_matrix_v_N_S)
rownames(shannon_matrix_v_N_S) = c("North", "South")
shannon_matrix_v_N_S

# Transpose and melt
tshannon_N_S_v = t(shannon_matrix_v_N_S)
tshannon_N_S_v
melt_shannon_N_S_v = melt(tshannon_N_S_v)
melt_shannon_N_S_v
colnames(melt_shannon_N_S_v) = c("1", "North_South", "Shannon Index")
melt_shannon_N_S_v
#remove extra rows from North_South data
melt_shannon_N_S_v <- melt_shannon_N_S_v[-c(16, 15, 14, 13),]
melt_shannon_N_S_v


# Plot Shannon index by Location_Year
shannon_plot_N_S_v = ggplot(melt_shannon_N_S_v, aes(x=North_South, y=`Shannon Index`, fill=North_South)) + 
  geom_boxplot(outlier.colour = NULL) + geom_jitter(color="black", size=2, alpha=0.2, height = 0) + ggtitle("Shannon Index per North_South vertebrate")
shannon_plot_N_S_v


# Use Welches T-test as it is more reliable when the two samples have unequal variances and possibly unequal sample sizes
North_v <- c(0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.01267017, 0.29239496, 0.00000000, 0.00000000)
South_v <- c(0.4510509, 0.0000000, 0.0000000, 0.0000000)
t.test(North_v, South_v)
```


```{r Alpha Diversity species- shannon bat metagenome viruses only}
only.data <- read.csv("only_bat_metagenome.csv")
only.data

only.data.abundances = only.data[, 2:10]
only.data.abundances

t.only.data.abundances = t(only.data.abundances)
t.only.data.abundances

colnames(t.only.data.abundances) <- c("B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11", "B12")
t.only.data.abundances

shannon_only = apply(t.only.data.abundances,2,diversity,index="shannon") 
shannon_only

shannon_matrix = as.matrix(shannon_only)
shannon_matrix

metadata <- read.csv("vertebrate_standardised_abundance.csv", header=TRUE)
metadata
shannon_matrix_species = cbind(shannon_matrix, metadata$Species)
shannon_matrix_species

colnames(shannon_matrix_species) = c("Shannon", "Species")
shannon_matrix_species

# Extract species
M.tuberculata = shannon_matrix_species[c(1,2,3,4,7,8,11),]
M.tuberculata
C.tuberculatus = shannon_matrix_species[c(5,6,9,10,12),]
C.tuberculatus

shannon_matrix = t(as.matrix(merge(zoo(M.tuberculata[,1]), zoo(C.tuberculatus[,1]))))
shannon_matrix
class(shannon_matrix) = "numeric"
class(shannon_matrix)
rownames(shannon_matrix) = c("M.tuberculata", "C.tuberculatus")
shannon_matrix


tshannon = t(shannon_matrix)
tshannon
melt_shannon = melt(tshannon)
melt_shannon
colnames(melt_shannon) = c("1", "Species", "Shannon Index")
melt_shannon
#remove extra two rows from C.tuberculatus
melt_shannon <- melt_shannon[-(13:14),]
melt_shannon

shannon_plot_species = ggplot(melt_shannon, aes(x=Species, y=`Shannon Index`, fill=Species)) + 
  geom_boxplot() + geom_jitter(color="black", size=2, alpha=0.2, height=0) + ggtitle("Shannon Index per Species Vertebrate Metagenome viruses only")
shannon_plot_species

#p-value 0.04429

M.tuberculata <- c(0.2375336, 0.9305648, 1.1357301, 0.9110898, 0.0000000, 0.6071758, 0.3735534)
C.tuberculatus <- c(0.5903882, 0.1687802, 0.0000000, 0.0000000, 0.0000000)
t.test(M.tuberculata, C.tuberculatus)




```


```{r Alpha Diversity north/south- shannon bat viruses only}
##North and South bat metagenome viruses only
t.only.data.abundances = as.data.frame(t.only.data.abundances)
t.only.data.abundances

shannon_only = apply(as.matrix(t.only.data.abundances),2,diversity,index="shannon") 
shannon_only

# Box plot: Shannon diversity
shannon_matrix = as.matrix(shannon_only)
shannon_matrix
metadata <- read.csv("vertebrate_standardised_abundance.csv", header=TRUE)
metadata
shannon_matrix_N_S = cbind(shannon_matrix, metadata$North_South)
shannon_matrix_N_S
colnames(shannon_matrix_N_S) = c("Shannon", "North_South")
shannon_matrix_N_S


# Extract North_South and manually change the dimension of those that only have one row of data
North = shannon_matrix_N_S[c(1, 2, 3, 4, 5, 6, 7, 8),]
North
South = shannon_matrix_N_S[c(9, 10, 11, 12),]
South

# Combine species as separate rows and transpose data

shannon_matrix_N_S = t(as.matrix(merge(zoo(North[,1]), zoo(South[,1]))))
shannon_matrix_N_S
class(shannon_matrix_N_S) = "numeric"
class(shannon_matrix_N_S)
rownames(shannon_matrix_N_S) = c("North", "South")
shannon_matrix_N_S

# Transpose and melt
tshannon_N_S = t(shannon_matrix_N_S)
tshannon_N_S
melt_shannon_N_S = melt(tshannon_N_S)
melt_shannon_N_S
colnames(melt_shannon_N_S) = c("1", "North_South", "Shannon Index")
melt_shannon_N_S
#remove extra rows from North_South data
melt_shannon_N_S <- melt_shannon_N_S[-c(16, 15, 14, 13),]
melt_shannon_N_S


# Plot Shannon index by North_south
shannon_plot_N_S = ggplot(melt_shannon_N_S, aes(x=North_South, y=`Shannon Index`, fill=North_South)) + 
  geom_boxplot() + geom_jitter(color="black", size=2, alpha=0.2, height=0) + ggtitle("Shannon Index per North_South vertebrate metaegenome viruses only")
shannon_plot_N_S

# Use Welches T-test as it is more reliable when the two samples have unequal variances and possibly unequal sample sizes
#pvalue= 0.01913 significant
North <- c(0.2375336, 0.9305648, 1.1357301, 0.9110898, 0.5903882, 0.1687802, 0.0000000, 0.6071758)
South <- c(0.0000000, 0.00000000, 0.3735534, 0.0000000)
t.test(North, South)

```

```{r distance metrix of bat viruses}
shannon.vertebrate
shannon_matrix_vertebrate_full_data  = t(outer(shannon.vertebrate, shannon.vertebrate,'-'))
shannon_matrix_vertebrate_full_data
write.csv(shannon_matrix_vertebrate_full_data, file="vertebrate_matrix.csv")

shannon_combined
shannon_matrix_combined  = t(outer(shannon_combined, shannon_combined,'-'))
shannon_matrix_combined
write.csv(shannon_matrix_combined, file="combined_matrix.csv")

shannon_only
shannon_matrix_only  = t(outer(shannon_only, shannon_only,'-'))
shannon_matrix_only
write.csv(shannon_matrix_only, file="only_matrix.csv")
```


```{r distance matrix of bat viruses}
#only metagenome viruses 
only_matrix_final <- read_csv("only_matrix_final.csv")
only_matrix_final

only_matrix_final_plot <- ggplot(only_matrix_final, aes(x= Distance_km, y=Shannon_difference)) + geom_point() +
  geom_smooth(mapping = aes(x = Distance_km, y = Shannon_difference), method="lm", formula = y ~ x) + 
  theme_minimal()
only_matrix_final_plot

cor(x = only_matrix_final$Distance_km, y = only_matrix_final$Shannon_difference)
cor.test(x= only_matrix_final$Distance_km, y= only_matrix_final$Shannon_difference, method=c("pearson"))

#only vertebrate viruses
vertebrate_matrix_final <- read_csv("vertebrate_matrix_final.csv")
vertebrate_matrix_final

vertebrate_matrix_final_plot <- ggplot(vertebrate_matrix_final, aes(x= Distance_km, y=Shannon_difference)) + geom_point() +
  geom_smooth(mapping = aes(x = Distance_km, y = Shannon_difference), method="lm", formula = y ~ x) + 
  theme_minimal()
vertebrate_matrix_final_plot

cor(x = vertebrate_matrix_final$Distance_km, y = vertebrate_matrix_final$Shannon_difference)
cor.test(x= vertebrate_matrix_final$Distance_km, y= vertebrate_matrix_final$Shannon_difference, method=c("pearson"))

#combine vertebrate and metagenome viruses
combined_matrix_final <- read_csv("combined_matrix_final.csv")
combined_matrix_final

combined_matrix_final_plot <- ggplot(combined_matrix_final, aes(x= Distance_km, y=Shannon_difference)) + geom_point() +
  geom_smooth(mapping = aes(x = Distance_km, y = Shannon_difference), method="lm", formula = y ~ x) + 
  theme_minimal()
combined_matrix_final_plot

cor(x = combined_matrix_final$Distance_km, y = combined_matrix_final$Shannon_difference)
cor.test(x= combined_matrix_final$Distance_km, y= combined_matrix_final$Shannon_difference, method=c("pearson"))




```
